
# smt run --config .config.yaml -X data/X_train.npy -y data/train_labels_new.csv -a fit
# module: ml_project.pipeline
# class: Pipeline
# params:
 # class_list:
module: ml_project.models.feature_selection
class: Run

  #  - module: ml_project.models.feature_selection
  #    class: RandomBinsExtraction
  #    params:
  #      splits: 5000
   #
  #  - module: sklearn.feature_selection
  #    class: VarianceThreshold
  #    params:
  #      threshold: 5.0
   #
  #  - module: sklearn.preprocessing
  #    class: StandardScaler
   #
  #  - module: sklearn.linear_model
  #    class: LogisticRegression
  #    params:
  #      C: 1.0
  #      solver: netwon-cg
  #      n_jobs: -1
